// <auto-generated />
using System;
using Core.Infraestructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Infraestructure.Persistance.Migrations
{
    [DbContext(typeof(ChatContext))]
    [Migration("20240208175840_MigracionInicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.Domain.Entities.Grupo", b =>
                {
                    b.Property<int>("Id_Grupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Grupo");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Core.Domain.Entities.Mensaje", b =>
                {
                    b.Property<int>("Id_Mensaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time(6)");

                    b.Property<int>("Id_Group")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Mensaje");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("Core.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Core.Domain.Entities.Mensaje", b =>
                {
                    b.HasOne("Core.Domain.Entities.Grupo", "Grupos")
                        .WithMany("Mensajes")
                        .HasForeignKey("Id_Mensaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("grupos_ibfk_1");

                    b.HasOne("Core.Domain.Entities.Usuario", "Usuarios")
                        .WithMany("Mensajes")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("usuarios_ibfk_1");

                    b.Navigation("Grupos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Core.Domain.Entities.Grupo", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("Core.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Mensajes");
                });
#pragma warning restore 612, 618
        }
    }
}
